### ISSUE TITLE
ddns_client: ConnectTimeoutError

### ISSUE THREAD

**Issue by ThomasWaldmann** [nsupdate-info/nsupdate.info#248]
```
[2015-11-30 19:16:09,720] ERROR the dyndns2 updater raised an exception [{'hostname': u'xxxxxx', 'secure': True, 'server': u'ipv6.tunnelbroker.net', 'myip': '2.2.2.2', 'path': u'/nic/update', 'name': u'xxx'
}] [ip: 2.2.2.2, ua: "Fritz!Box DDNS/1.0.1"]
Traceback (most recent call last):
  File "/srv/nsupdate.info/repo/nsupdate/api/views.py", line 446, in _on_update_success
    ddns_client.dyndns2_update(**kwargs)
  File "/srv/nsupdate.info/repo/nsupdate/utils/ddns_client.py", line 40, in dyndns2_update
    r = requests.get(url, params=params, auth=(name, password), timeout=timeout)
  File "/srv/nsupdate.info/env/local/lib/python2.7/site-packages/requests/api.py", line 60, in get
    return request('get', url, **kwargs)
  File "/srv/nsupdate.info/env/local/lib/python2.7/site-packages/requests/api.py", line 49, in request
    return session.request(method=method, url=url, **kwargs)
  File "/srv/nsupdate.info/env/local/lib/python2.7/site-packages/requests/sessions.py", line 457, in requ
est
    resp = self.send(prep, **send_kwargs)
  File "/srv/nsupdate.info/env/local/lib/python2.7/site-packages/requests/sessions.py", line 569, in send
    r = adapter.send(request, **kwargs)
  File "/srv/nsupdate.info/env/local/lib/python2.7/site-packages/requests/adapters.py", line 411, in send
    raise ConnectTimeout(e, request=request)
ConnectTimeout: HTTPSConnectionPool(host='ipv6.tunnelbroker.net', port=443): Max retries exceeded with url: /nic/update?hostname=xxxxxx&myip=2.2.2.2 (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f34f98fbcd0>, 'Connection to ipv6.tunnelbroker.net timed  out. (connect timeout=30.0)'))
```

**Comment by ThomasWaldmann** [comment]
This is already fixed:
```
            try:
                ddns_client.dyndns2_update(**kwargs)
            except Exception:
                # we never want to crash here
                kwargs.pop('password')
                logger.exception("the dyndns2 updater raised an exception [%r]" % kwargs)
```
