### ISSUE TITLE
crash when trying to register

### ISSUE THREAD

**Issue by ThomasWaldmann** [nsupdate-info/nsupdate.info#292]
```
Internal Server Error: /account/register/
Traceback (most recent call last):
  File "/srv/nsupdate.info/env/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/srv/nsupdate.info/env/local/lib/python2.7/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/srv/nsupdate.info/env/local/lib/python2.7/site-packages/registration/views.py", line 79, in dispatch
    return super(RegistrationView, self).dispatch(request, *args, **kwargs)
  File "/srv/nsupdate.info/env/local/lib/python2.7/site-packages/django/views/generic/base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "/srv/nsupdate.info/env/local/lib/python2.7/site-packages/registration/views.py", line 35, in post
    return self.form_valid(request, form)
  File "/srv/nsupdate.info/env/local/lib/python2.7/site-packages/registration/views.py", line 82, in form_valid
    new_user = self.register(request, **form.cleaned_data)
  File "/srv/nsupdate.info/env/local/lib/python2.7/site-packages/registration/backends/default/views.py", line 91, in register
    request=request,
  File "/srv/nsupdate.info/env/local/lib/python2.7/site-packages/registration/models.py", line 91, in create_inactive_user
    registration_profile = self.create_profile(new_user)
  File "/srv/nsupdate.info/env/local/lib/python2.7/site-packages/registration/models.py", line 115, in create_profile
    activation_key=activation_key)
  File "/srv/nsupdate.info/env/local/lib/python2.7/site-packages/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/srv/nsupdate.info/env/local/lib/python2.7/site-packages/django/db/models/query.py", line 348, in create
    obj.save(force_insert=True, using=self.db)
  File "/srv/nsupdate.info/env/local/lib/python2.7/site-packages/django/db/models/base.py", line 734, in save
    force_update=force_update, update_fields=update_fields)
  File "/srv/nsupdate.info/env/local/lib/python2.7/site-packages/django/db/models/base.py", line 762, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/srv/nsupdate.info/env/local/lib/python2.7/site-packages/django/db/models/base.py", line 846, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/srv/nsupdate.info/env/local/lib/python2.7/site-packages/django/db/models/base.py", line 885, in _do_insert
    using=using, raw=raw)
  File "/srv/nsupdate.info/env/local/lib/python2.7/site-packages/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/srv/nsupdate.info/env/local/lib/python2.7/site-packages/django/db/models/query.py", line 920, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/srv/nsupdate.info/env/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 974, in execute_sql
    cursor.execute(sql, params)
  File "/srv/nsupdate.info/env/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/srv/nsupdate.info/env/local/lib/python2.7/site-packages/django/db/utils.py", line 98, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/srv/nsupdate.info/env/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/srv/nsupdate.info/env/local/lib/python2.7/site-packages/django/db/backends/sqlite3/base.py", line 318, in execute
    return Database.Cursor.execute(self, query, params)
IntegrityError: NOT NULL constraint failed: registration_registrationprofile.activated
```

**Comment by ThomasWaldmann** [comment]
maybe this is related to trying to register a new account for an already existing username / email.

**Comment by ThomasWaldmann** [comment]
Hmm, when using the register form it would tell "A user with that username already exists."

**Comment by ThomasWaldmann** [comment]
unclear, likely not our code, not sure if it still happens, closing.
