### ISSUE TITLE
incorrect padding for binascii.a2b_base64

### ISSUE THREAD

**Issue by ThomasWaldmann** [nsupdate-info/nsupdate.info#319]
```
Internal Server Error: /domain/1169/
Traceback (most recent call last):
  File "/srv/nsupdate.info/env/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/srv/nsupdate.info/env/local/lib/python2.7/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/srv/nsupdate.info/env/local/lib/python2.7/site-packages/django/utils/decorators.py", line 34, in _wrapper
    return bound_func(*args, **kwargs)
  File "/srv/nsupdate.info/env/local/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/srv/nsupdate.info/env/local/lib/python2.7/site-packages/django/utils/decorators.py", line 30, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/srv/nsupdate.info/repo/nsupdate/main/views.py", line 469, in dispatch
    return super(DomainView, self).dispatch(*args, **kwargs)
  File "/srv/nsupdate.info/env/local/lib/python2.7/site-packages/django/views/generic/base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "/srv/nsupdate.info/env/local/lib/python2.7/site-packages/django/views/generic/edit.py", line 272, in post
    return super(BaseUpdateView, self).post(request, *args, **kwargs)
  File "/srv/nsupdate.info/env/local/lib/python2.7/site-packages/django/views/generic/edit.py", line 214, in post
    if form.is_valid():
  File "/srv/nsupdate.info/env/local/lib/python2.7/site-packages/django/forms/forms.py", line 184, in is_valid
    return self.is_bound and not self.errors
  File "/srv/nsupdate.info/env/local/lib/python2.7/site-packages/django/forms/forms.py", line 176, in errors
    self.full_clean()
  File "/srv/nsupdate.info/env/local/lib/python2.7/site-packages/django/forms/forms.py", line 393, in full_clean
    self._clean_form()
  File "/srv/nsupdate.info/env/local/lib/python2.7/site-packages/django/forms/forms.py", line 417, in _clean_form
    cleaned_data = self.clean()
  File "/srv/nsupdate.info/repo/nsupdate/main/forms.py", line 71, in clean
    check_domain(self.instance.name)
  File "/srv/nsupdate.info/repo/nsupdate/main/dnstools.py", line 117, in check_domain
    add(fqdn, socket.inet_ntoa(struct.pack('>I', random.randint(1, 0xffffffff))))
  File "/srv/nsupdate.info/repo/nsupdate/main/dnstools.py", line 155, in add
    update_ns(fqdn, rdtype, ipaddr, action=action, ttl=ttl)
  File "/srv/nsupdate.info/repo/nsupdate/main/dnstools.py", line 335, in update_ns
    keyring=dns.tsigkeyring.from_text({keyname: key}),
  File "/srv/nsupdate.info/env/local/lib/python2.7/site-packages/dns/tsigkeyring.py", line 33, in from_text
    secret = base64.decodestring(maybe_encode(textring[keytext]))
  File "/usr/lib/python2.7/base64.py", line 321, in decodestring
    return binascii.a2b_base64(s)
Error: Incorrect padding
```

**Comment by DanielO** [comment]
I had this, the secret is too long for the field and gets truncated.
```
--- ./nsupdate/main/models.py.orig      2018-04-12 13:33:26.221719000 +0000
+++ ./nsupdate/main/models.py   2018-04-12 13:33:35.901131000 +0000
@@ -99,7 +99,7 @@
         help_text=_("IP where DNS queries for this zone will be sent to"))
     nameserver_update_secret = models.CharField(
         _("nameserver update secret"),
-        max_length=88,  # 512 bits base64 -> 88 bytes
+        max_length=90,  # 512 bits base64
         default='',
         help_text=_("Shared secret that allows updating this zone (base64 encoded)"))
     nameserver_update_algorithm = models.CharField(
```

Although after this patch it complains it can't set/delete connectivity-test.mydomain :(

**Comment by DanielO** [comment]
Ah wait, I just realised my issue..
I ran "dnssec-keygen -a HMAC-SHA512 -b 512 -n ENTITY ddns" and copied the key from the .key file which is 89 bytes long but the .private key is 88 characters long.

I have absolutely no idea why they are different though!
