### ISSUE TITLE
traceback in update

### ISSUE THREAD

**Issue by ThomasWaldmann** [nsupdate-info/nsupdate.info#337]
similar to #335:

```
Internal Server Error: /nic/update
Traceback (most recent call last):
  File "/srv/nsupdate.info/env/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/srv/nsupdate.info/env/local/lib/python2.7/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/srv/nsupdate.info/env/local/lib/python2.7/site-packages/django/views/generic/base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "/srv/nsupdate.info/repo/nsupdate/utils/log.py", line 124, in caller
    return func(*args, **kwargs)
  File "/srv/nsupdate.info/repo/nsupdate/api/views.py", line 240, in get
    return _update_or_delete(host, ipaddr, secure, logger=logger, _delete=delete)
  File "/srv/nsupdate.info/repo/nsupdate/api/views.py", line 364, in _update_or_delete
    update(fqdn, ipaddr)
  File "/srv/nsupdate.info/repo/nsupdate/main/dnstools.py", line 206, in update
    current_ipaddr = query_ns(fqdn, rdtype)
  File "/srv/nsupdate.info/repo/nsupdate/main/dnstools.py", line 255, in query_ns
    answer = resolver.query(str(fqdn), rdtype)
  File "/srv/nsupdate.info/env/local/lib/python2.7/site-packages/dns/resolver.py", line 962, in query
    source_port=source_port)
  File "/srv/nsupdate.info/env/local/lib/python2.7/site-packages/dns/query.py", line 257, in udp
    one_rr_per_rrset=one_rr_per_rrset)
  File "/srv/nsupdate.info/env/local/lib/python2.7/site-packages/dns/message.py", line 807, in from_wire
    reader.read()
  File "/srv/nsupdate.info/env/local/lib/python2.7/site-packages/dns/message.py", line 748, in read
    self._get_section(self.message.additional, adcount)
  File "/srv/nsupdate.info/env/local/lib/python2.7/site-packages/dns/message.py", line 681, in _get_section
    raise UnknownTSIGKey('got signed message without keyring')
UnknownTSIGKey: got signed message without keyring

Request repr(): 
<WSGIRequest
path:/nic/update,
GET:<QueryDict: {}>,
POST:<QueryDict: {}>,
COOKIES:{},
META:{'CONTENT_LENGTH': '',
 'CONTENT_TYPE': '',
 u'CSRF_COOKIE': u'g26zYGheA3UYzN4ax4Uw8SkhmMAWqGLK',
 'DOCUMENT_ROOT': '/srv/nsupdate.info/htdocs',
 'HTTP_ACCEPT': '*/*',
 'HTTP_AUTHORIZATION': 'Basic ...',
 'HTTP_CONNECTION': 'close',
 'HTTP_HOST': 'ipv4.nsupdate.info',
 'HTTP_USER_AGENT': 'Synology DDNS Updater/15266 support@synology.com',
 'HTTP_X_FORWARDED_FOR': '212.51.140.197',
 'HTTP_X_FORWARDED_PROTO': 'https',
 'HTTP_X_REAL_IP': '212.51.140.197',
 'PATH_INFO': u'/nic/update',
 'QUERY_STRING': '',
 'REMOTE_ADDR': '212.51.140.197',
 'REMOTE_PORT': '',
 'REQUEST_METHOD': 'GET',
 'REQUEST_URI': '/nic/update',
 u'SCRIPT_NAME': u'',
 'SERVER_NAME': 'www.nsupdate.info',
 'SERVER_PORT': '80',
 'SERVER_PROTOCOL': 'HTTP/1.0',
 }>
```

**Comment by alainwolf** [comment]
Yes, probably same user account as in #335 as the IP is the IPv4 equivalent of the IPv6 in there.
