### ISSUE TITLE
traceback in register, unique constraint failed

### ISSUE THREAD

**Issue by ThomasWaldmann** [nsupdate-info/nsupdate.info#339]
```
Internal Server Error: /account/register/
Traceback (most recent call last):
  File "/srv/nsupdate.info/env/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/srv/nsupdate.info/env/local/lib/python2.7/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/srv/nsupdate.info/env/local/lib/python2.7/site-packages/django/utils/decorators.py", line 34, in _wrapper
    return bound_func(*args, **kwargs)
  File "/srv/nsupdate.info/env/local/lib/python2.7/site-packages/django/views/decorators/debug.py", line 76, in sensitive_post_parameters_wrapper
    return view(request, *args, **kwargs)
  File "/srv/nsupdate.info/env/local/lib/python2.7/site-packages/django/utils/decorators.py", line 30, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/srv/nsupdate.info/env/local/lib/python2.7/site-packages/registration/views.py", line 39, in dispatch
    return super(RegistrationView, self).dispatch(request, *args, **kwargs)
  File "/srv/nsupdate.info/env/local/lib/python2.7/site-packages/django/views/generic/base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "/srv/nsupdate.info/env/local/lib/python2.7/site-packages/django/views/generic/edit.py", line 215, in post
    return self.form_valid(form)
  File "/srv/nsupdate.info/env/local/lib/python2.7/site-packages/registration/views.py", line 42, in form_valid
    new_user = self.register(form)
  File "/srv/nsupdate.info/env/local/lib/python2.7/site-packages/registration/backends/default/views.py", line 87, in register
    new_user_instance = form.save()
  File "/srv/nsupdate.info/env/local/lib/python2.7/site-packages/django/contrib/auth/forms.py", line 95, in save
    user.save()
  File "/srv/nsupdate.info/env/local/lib/python2.7/site-packages/django/db/models/base.py", line 734, in save
    force_update=force_update, update_fields=update_fields)
  File "/srv/nsupdate.info/env/local/lib/python2.7/site-packages/django/db/models/base.py", line 762, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/srv/nsupdate.info/env/local/lib/python2.7/site-packages/django/db/models/base.py", line 846, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/srv/nsupdate.info/env/local/lib/python2.7/site-packages/django/db/models/base.py", line 885, in _do_insert
    using=using, raw=raw)
  File "/srv/nsupdate.info/env/local/lib/python2.7/site-packages/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/srv/nsupdate.info/env/local/lib/python2.7/site-packages/django/db/models/query.py", line 920, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/srv/nsupdate.info/env/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 974, in execute_sql
    cursor.execute(sql, params)
  File "/srv/nsupdate.info/env/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/srv/nsupdate.info/env/local/lib/python2.7/site-packages/django/db/utils.py", line 98, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/srv/nsupdate.info/env/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/srv/nsupdate.info/env/local/lib/python2.7/site-packages/django/db/backends/sqlite3/base.py", line 318, in execute
    return Database.Cursor.execute(self, query, params)
IntegrityError: UNIQUE constraint failed: auth_user.username

Request repr(): 
<WSGIRequest
path:/account/register/,
GET:<QueryDict: {}>,
POST:<QueryDict: {u'csrfmiddlewaretoken': [u'0x4...A'], u'password2': [u'********************'], u'password1': [u'********************'], u'submit': [u'Send activation email'], u'username': [u'AaronHaimi'], u'email': [u'...']}>,
COOKIES:{'csrftoken': '0x4...A',
 'sessionid': 'f...3'},
META:{'CONTENT_LENGTH': '169',
 'CONTENT_TYPE': 'application/x-www-form-urlencoded',
 u'CSRF_COOKIE': u'0x4...A',
 'DOCUMENT_ROOT': '/srv/nsupdate.info/htdocs',
 'HTTP_ACCEPT': '*/*',
 'HTTP_CONNECTION': 'close',
 'HTTP_CONTENT_LENGTH': '169',
 'HTTP_CONTENT_TYPE': 'application/x-www-form-urlencoded',
 'HTTP_COOKIE': 'csrftoken=0x...A; sessionid=f...3',
 'HTTP_HOST': 'www.nsupdate.info',
 'HTTP_PRAGMA': 'no-cache',
 'HTTP_REFERER': 'https://www.nsupdate.info/account/register/',
 'HTTP_USER_AGENT': 'Mozilla/5.0 (Windows NT 10.1; Win64; rv:38.0) Gecko/20100101 Firefox/38.0',
 'HTTP_X_FORWARDED_FOR': '46.161.9.22',
 'HTTP_X_FORWARDED_PROTO': 'https',
 'HTTP_X_REAL_IP': '46.161.9.22',
 'PATH_INFO': u'/account/register/',
 'QUERY_STRING': '',
 'REMOTE_ADDR': '46.161.9.22',
 'REMOTE_PORT': '',
 'REQUEST_METHOD': 'POST',
 'REQUEST_URI': '/account/register/',
 u'SCRIPT_NAME': u'',
 'SERVER_NAME': 'www.nsupdate.info',
 'SERVER_PORT': '80',
 'SERVER_PROTOCOL': 'HTTP/1.0'}>
```

**Comment by ThomasWaldmann** [comment]
bug in django-registration-redux?

**Comment by ThomasWaldmann** [comment]
likely not in our code, closing.
